server:
  port: 8761 # or your preferred port

spring:
  application:
    name: eureka-server-user

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/