spring:
  application:
    name: dfs-app-b

server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # instance:
  #   preferIpAddress: true # Optional, for preferring IP address in registration